version: "3.8"
services:
  bentel-absoluta:
    image: "axtx2301/bentel-absoluta-local-bridge:latest"
    environment:
      TZ: "Europe/Rome"
      MQTT_ADDRESS: "<MQTT_ADDRESS>"
      MQTT_PORT: "<MQTT_PORT>"
      MQTT_USERNAME: "<MQTT_USERNAME>"
      MQTT_PASSWORD: "<MQTT_PASSWORD>"
      ALARM_ADDRESS: "<ALARM_ADDRESS>"
      ALARM_PIN: "<ALARM_PIN>"
      ALARM_PORT: "<ALARM_PORT>"
