name: Build Jars and Update Repo Addon

on:
  push:
    branches:
      - master

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Build absoluta.jar, protocol.jar
        run: |
          chmod +x build_secured.sh
          ./build_secured.sh

      - name: Build app.jar
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Clone Repo Addon
        run: |
          git clone https://x-access-token:${{ secrets.ADDONTOKEN }}@github.com/AlessandroTischer/ha-absoluta-local-bridge.git

      - name: Copy JARs to Repo Addon
        run: |
          cp secured/*.jar ha-absoluta-local-bridge/absoluta_local/secured/
          cp build/app.jar ha-absoluta-local-bridge/absoluta_local/app.jar

      - name: Update config.yaml version
        run: |
          VERSION=$(grep 'VERSION = ' src/Application.java | sed -E 's/.*"([^"]+)".*/\1/')
          CONFIG_FILE="ha-absoluta-local-bridge/absoluta_local/config.yaml"
          if [ -f "$CONFIG_FILE" ]; then
            sed -i "s/^version: .*/version: '$VERSION'/" "$CONFIG_FILE"
          else
            echo "Attenzione: $CONFIG_FILE non trovato!"
          fi

      - name: Commit and Push to Repo Addon
        run: |
          cd ha-absoluta-local-bridge
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add .
          COMMIT_MSG="Updated jars because of update on main repository: $(git -C .. log -1 --pretty=%B)"
          git commit -m "$COMMIT_MSG" || echo "No changes to commit"
          git push
